---
version: dev
slug: devops-agent
name: DevOps Agent
description: Host your own Azure-DevOps Agent
arch:
  - aarch64
url: https://github.com/Mauwii/HA-DevOps-Agent
codenotary: mauwii@outlook.de
init: false
map:
  - config:rw
options:
  agentname: "HomeAssistant"
  pool: "local"
  organization: "https://dev.azure.com/Mauwii"
  token: "qdl6wrszjlx6gco5dov2gdb4x6326nc5zbs7xhapnxw2wkasbxpq"
schema:
  agentname: str
  pool: str
  organization: url
  token: password
