---
name: DevOps-Agent
description: Host your own Azure-DevOps Agent
version: dev
slug: ha-devops-agent
arch:
  - aarch64
url: https://github.com/mauwii/ha-devops-agent
codenotary: Mauwii@outlook.de
init: false
map:
  - config:rw
options:
  install_packages: []
  init_commands: []
  agentname: "HomeAssistant"
  pool: "Default"
  organization: "https://dev.azure.com/<your organization>"
  token: "<your personal access token>"
schema:
  install_packages:
    - str
  init_commands:
    - str
  agentname: str
  pool: str
  organization: url
  token: password
